# Routes package initialization
from .auth_routes import get_auth_routes
from .user_routes import get_user_routes
from .worker_routes import get_worker_routes
from .company_routes import get_company_routes
from .admin_routes import get_admin_routes
from .job_offer_routes import get_job_offer_routes
from .application_routes import get_application_routes
from .job_routes import get_job_routes
from .payment_routes import get_payment_routes
from .review_routes import get_review_routes
from .base_routes import BaseRoutes